services:
  - type: web
    name: caregivers-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: caregivers-db
          property: connectionString